# Generated by Django 6.0.5 on 2026-05-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketComparable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('sale', 'Sale'), ('asking', 'Asking Price'), ('rent', 'Rental')], max_length=20)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('land', 'Land'), ('commercial', 'Commercial')], max_length=30)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('sheet', models.CharField(blank=True, max_length=50)),
                ('plan', models.CharField(blank=True, max_length=50)),
                ('parcel_number', models.CharField(max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('planning_zone', models.CharField(blank=True, max_length=50)),
                ('building_density', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('coverage_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('floors', models.PositiveIntegerField(blank=True, null=True)),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('geometry_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
